"""
Validated TREX <-> P3DH semantic equivalence mappings.

Generated by scripts/validate_semantic_equivalence.py
Validated at 2025-06-30 with 3+ overlapping banks, <1% difference.

Format:
    TREX_ITEM: (P3DH_template, P3DH_row, matching_banks, avg_diff_pct)
"""

VALIDATED_MAPPINGS = {
    # KM1 - Key Metrics
    ("Capital", 2520102): ("K_61.00", "0010", 5, 0.00),   # CET1 Capital
    ("Capital", 2520133): ("K_61.00", "0020", 5, 0.00),   # Tier1 Capital  
    ("Capital", 2520101): ("K_61.00", "0030", 5, 0.00),   # Total Capital
    ("RWA OV1", 2520220): ("K_61.00", "0040", 5, 0.00),   # Total RWA
    ("Capital", 2520140): ("K_61.00", "0050", 5, 0.01),   # CET1 Ratio
    ("Capital", 2520141): ("K_61.00", "0060", 5, 0.00),   # Tier1 Ratio
    ("Capital", 2520142): ("K_61.00", "0070", 5, 0.00),   # Total Capital Ratio
    
    # CC1 - Capital Composition
    ("Capital", 2520102): ("K_66.01", "0370", 17, 0.00),
    ("Capital", 2520110): ("K_66.01", "0130", 17, 0.00),
    ("Capital", 2520138): ("K_66.01", "0730", 17, 0.00),
    ("Capital", 2520141): ("K_66.01", "0750", 17, 0.00),
    ("Capital", 2520142): ("K_66.01", "0760", 17, 0.00),
    ("Capital", 2520140): ("K_66.01", "0740", 17, 0.00),
    ("Capital", 2520133): ("K_66.01", "0550", 17, 0.00),
    
    # CC2 - Reconciliation
    ("Assets", 2521010): ("K_66.02", "0010", 15, 0.01),
    ("Liabilities", 2521217): ("K_66.02", "0010", 15, 0.01),
    
    # CCyB - Countercyclical Buffer
    ("Capital", 2520138): ("K_67.02", "0010", 15, 0.00),
    ("RWA OV1", 2520220): ("K_67.02", "0010", 15, 0.00),
    ("RWA OV1", 2520221): ("K_67.02", "0010", 14, 0.00),
    
    # LR1 - Leverage Ratio
    ("Leverage", 2520903): ("K_70.00", "0150", 17, 0.00),
    
    # LR2 - Leverage Ratio Disclosure
    ("Leverage", 2520901): ("K_71.00", "0430", 15, 0.00),
    ("Capital", 2520133): ("K_71.00", "0430", 15, 0.00),
    ("Leverage", 2520905): ("K_71.00", "0450", 14, 0.03),
    ("Leverage", 2520903): ("K_71.00", "0440", 14, 0.00),
    
    # LR3 - Split-up
    ("Assets", 2521002): ("K_72.00", "0020", 5, 0.24),
    
    # CR1 - Performing/Non-performing
    ("NPE", 2520608): ("K_21.01", "0010", 13, 0.07),
    
    # CR2 - NPL Changes
    ("NPE", 2520603): ("K_22.01", "0060", 10, 0.00),
    
    # CR3 - CRM Techniques
    ("NPE", 2520621): ("K_23.00", "0040", 16, 0.00),
    ("NPE", 2520623): ("K_23.00", "0040", 15, 0.01),
    
    # CR4 - Standardized RWA
    ("RWA OV1", 2520202): ("K_24.00", "0260", 17, 0.01),
    
    # CR5 - Standardized
    ("Credit Risk_STA_a", 2520522): ("K_25.00", "0010", 12, 0.18),
    
    # CR6 - IRB RWA
    ("RWA OV1", 2520204): ("K_26.00", "0190", 8, 0.00),
    
    # CR7 - IRB CRM
    ("RWA OV1", 2520204): ("K_27.01", "0310", 8, 0.10),
    ("RWA OV1", 2520204): ("K_27.02", "0130", 13, 0.06),
    
    # MR1 - Market Risk
    ("Market Risk", 2520401): ("K_10.00", "0090", 12, 0.23),
    
    # MR2-A - IMA
    ("Market Risk", 2520431): ("K_11.00", "0060", 8, 0.01),
    
    # MR3 - IMA Values
    ("Market Risk", 2520461): ("K_13.00", "0120", 8, 0.01),
    
    # CQ1 - Forborne
    ("Forborne exposures", 2520703): ("K_80.00", "0020", 13, 0.00),
    
    # CQ4 - NPE by Geography
    ("NPE", 2520606): ("K_83.01", "0030", 12, 0.00),
    
    # CQ5 - NPE by Industry
    ("NACE", 2521301): ("K_84.01", "0010", 13, 0.02),
    
    # ESG Templates
    ("NACE", 2521301): ("K_41.00", "0020", 10, 0.04),  # Climate
    ("NACE", 2521301): ("K_45.00", "0010", 6, 0.05),   # Physical Risk
    
    # MREL
    ("Capital", 2520138): ("K_90.01", "0030", 10, 0.01),
    ("RWA OV1", 2520221): ("K_90.01", "0030", 10, 0.01),
}


def get_trex_to_p3dh_mapping(trex_template: str, trex_item: int):
    """Get P3DH template and row for a TREX item."""
    key = (trex_template, trex_item)
    return VALIDATED_MAPPINGS.get(key)


def get_all_mappings():
    """Return all validated mappings."""
    return VALIDATED_MAPPINGS
